%YAML:1.0
# DAHENG Galaxy + Livox MID70
K_0: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [2506.3282850376445, 0.0, 628.0499117402735,
          0.0, 2507.378510578292, 521.6286659975834,
          0.0, 0.0, 1.0]

C_0: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [-0.06033446820774841, 0.9109649887427801,
          0.0005711348690384457, -0.00135738319718246,
          0.0]

# E_0: extrinsic matrix (LiDAR -> Camera), p_camera = E_0 * p_lidar
E_0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0121302861178385, -0.9999140209028614, 0.0049806586484032, -0.1336342239104681,
          -0.0096750236746827, -0.0050981599433497, -0.9999401995529967, 0.1822087188993382,
          0.9998796177918592, 0.0120813727309678, -0.0097360339636698, 0.1189569495057451,
          0.0, 0.0, 0.0, 1.0]
